vsphere_server = "vcenter.demo.com"
vsphere_dc_name = "DC"
vsphere_compute_cluster = "Cluster1"
vsphere_template = "terraform-demo-template"
vsphere_network = "VLAN1"
vsphere_datastore = "Datastore1"
vm_folder = "/Terraform-Demo"
